name: maven on ubuntu

# 每次提交一个新的commit到仓库都执行此工作流
on: [ push ]

jobs:
  # 设置任务key, 当没有设置name的时候显示这个值
  build:
    # 在指定的系统上运行
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11    # The Jdk version to make available on the path
          architecture: x64   # (x64 or x86) - defaults to x64
          java-package: jdk   # (jre, jdk or jdk+fx) - defaults to jdk

      - name: java version
        run: java -version

      - name: Build with Gradle
        run: mvn -DskipTests=true package

      - uses: actions/upload-artifact@v2
        with:
          name: Package-Maven
          path: build/libs